#!/usr/bin/env python3
"""Generate generated/R.swift from Localizable.xcstrings and Assets.xcassets."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path


SWIFT_KEYWORDS = {
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open", "operator",
    "private", "protocol", "public", "rethrows", "static", "struct", "subscript",
    "typealias", "var", "break", "case", "continue", "default", "defer", "do",
    "else", "fallthrough", "for", "guard", "if", "in", "repeat", "return",
    "switch", "where", "while", "as", "catch", "false", "is", "nil", "super",
    "self", "Self", "throw", "throws", "true", "try",
}


def swift_identifier(value: str) -> str:
    words = [word for word in re.split(r"[^A-Za-z0-9]+", value) if word]
    if not words:
        return "key_" + hashlib.sha256(value.encode()).hexdigest()[:12]
    identifier = words[0].lower() + "".join(word[:1].upper() + word[1:] for word in words[1:])
    if identifier[:1].isdigit():
        identifier = "_" + identifier
    if identifier in SWIFT_KEYWORDS:
        identifier += "Value"
    return identifier


def load_strings(path: Path) -> list[tuple[str, str]]:
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    return unique_identifiers(data.get("strings", {}).keys())


def load_images(path: Path) -> list[tuple[str, str]]:
    if not path.exists():
        return []
    names = sorted(item.stem for item in path.rglob("*.imageset"))
    return unique_identifiers(names)


def unique_identifiers(values) -> list[tuple[str, str]]:
    result: list[tuple[str, str]] = []
    used: set[str] = set()
    for value in sorted(values):
        identifier = swift_identifier(value)
        if identifier in used:
            identifier += "_" + hashlib.sha256(value.encode()).hexdigest()[:8]
        used.add(identifier)
        result.append((identifier, value))
    return result


def swift_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_group(name: str, values: list[tuple[str, str]]) -> list[str]:
    lines = [f"    enum {name} {{"]
    lines.extend(
        f'        static let {identifier} = "{swift_escape(value)}"'
        for identifier, value in values
    )
    lines.append("    }")
    return lines


def main() -> None:
    source_dir = Path(__file__).resolve().parent
    output = source_dir / "generated" / "R.swift"
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// AUTO-GENERATED by generate_r_swift.py — do not edit.",
        "import Foundation",
        "",
        # nonisolated：本 target 开了 SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor，
        # 不写的话这些资源键会被推成主 actor 隔离，非主线程的代码（后台解码、
        # Task.detached 里的文件读取等）取不到自己的错误文案。
        # 内容全是不可变的 String 常量，跨线程读本来就安全。
        "nonisolated enum R {",
        *render_group("Strings", load_strings(source_dir / "Localizable.xcstrings")),
        *render_group("Images", load_images(source_dir / "Assets.xcassets")),
        "}",
        "",
    ]
    content = "\n".join(lines)
    if not output.exists() or output.read_text(encoding="utf-8") != content:
        output.write_text(content, encoding="utf-8")
        print(f"[R] generated {output}")
    else:
        print(f"[R] unchanged {output}")


if __name__ == "__main__":
    main()
