#!/bin/bash
# Generate filego/generated/BuildLAN.swift with the Mac's current LAN address.
set -euo pipefail

if [ "${CONFIGURATION:-Debug}" != "Debug" ]; then
    echo "[inject-lan-ip] skip (${CONFIGURATION:-unknown})"
    exit 0
fi

HOST="$(ipconfig getifaddr en0 2>/dev/null || true)"
if [ -z "$HOST" ]; then
    HOST="$(ipconfig getifaddr en1 2>/dev/null || true)"
fi
if [ -z "$HOST" ]; then
    HOST="127.0.0.1"
fi

OUT_DIR="${SRCROOT}/filego/generated"
OUT="${OUT_DIR}/BuildLAN.swift"
mkdir -p "$OUT_DIR"

NEW_CONTENT="// AUTO-GENERATED by Scripts/inject-lan-ip.sh — do not edit.
// Configuration: ${CONFIGURATION:-Debug}
enum BuildLAN { static let host = \"${HOST}\" }
"

if [ -f "$OUT" ] && [ "$(cat "$OUT")" = "$NEW_CONTENT" ]; then
    echo "[inject-lan-ip] BuildLAN.host=${HOST} (unchanged)"
else
    printf "%s" "$NEW_CONTENT" > "$OUT"
    echo "[inject-lan-ip] BuildLAN.host=${HOST} -> ${OUT}"
fi
