#!/bin/bash
# Generate filego/generated/BuildLAN.swift with the Mac's current LAN address.
set -euo pipefail

if [ "${CONFIGURATION:-Debug}" != "Debug" ]; then
    echo "[inject-lan-ip] skip (${CONFIGURATION:-unknown})"
    exit 0
fi

HOST="$(ipconfig getifaddr en0 2>/dev/null || true)"
if [ -z "$HOST" ]; then
    HOST="$(ipconfig getifaddr en1 2>/dev/null || true)"
fi
if [ -z "$HOST" ]; then
    HOST="127.0.0.1"
fi

OUT_DIR="${SRCROOT}/filego/generated"
OUT="${OUT_DIR}/BuildLAN.swift"
mkdir -p "$OUT_DIR"

# nonisolated：本 target 开了 SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor，
# 不写的话 BuildLAN.host 会被推成主 actor 隔离，而 BackendConfig 要在
# nonisolated 上下文里读它（详见 Network/FileGoTarget.swift 的说明）。
NEW_CONTENT="// AUTO-GENERATED by Scripts/inject-lan-ip.sh — do not edit.
// Configuration: ${CONFIGURATION:-Debug}
nonisolated enum BuildLAN { static let host = \"${HOST}\" }
"

if [ -f "$OUT" ] && [ "$(cat "$OUT")" = "$NEW_CONTENT" ]; then
    echo "[inject-lan-ip] BuildLAN.host=${HOST} (unchanged)"
else
    printf "%s" "$NEW_CONTENT" > "$OUT"
    echo "[inject-lan-ip] BuildLAN.host=${HOST} -> ${OUT}"
fi
